'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
function parseArgs(argv){const out={};for(const item of argv){if(!item.startsWith('--'))continue;const [k,...r]=item.slice(2).split('=');out[k]=r.length?r.join('='):true;}return out;}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8'));}
function sha256File(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');}
function sameSet(a,b){const x=[...new Set((a||[]).map(String))].sort(),y=[...new Set((b||[]).map(String))].sort();return x.length===y.length&&x.every((v,i)=>v===y[i]);}
function dbBacked(v){return Array.isArray(v)&&v.some(r=>r.scope==='db'&&/Connected to MySQL/i.test(String(r.message||'')));}
const a=parseArgs(process.argv.slice(2));const kind=String(a.kind||'');const profile=String(a.profile||'');const dir=path.resolve(String(a.dir||''));const contractPath=path.resolve(String(a.contract||process.env.MAPPING_CONTRACT_FILE||''));const manifestPath=path.resolve(String(a.manifest||process.env.SOURCE_MANIFEST_FILE||''));
if(!['profile','chunk'].includes(kind)||!profile||!dir||!contractPath||!manifestPath) throw new Error('Usage: --kind=profile|chunk --profile --dir --contract --manifest [--offset --limit --source-rows]');
const required=['summary.json','status.json','validation.json','reconciliation.json','fk_dependency_report.json'];for(const f of required){const p=path.join(dir,f);if(!fs.existsSync(p)) throw new Error(`Missing ${f}: ${p}`);}
const contract=readJson(contractPath),manifestSha=sha256File(manifestPath),summary=readJson(path.join(dir,'summary.json')),status=readJson(path.join(dir,'status.json')),validation=readJson(path.join(dir,'validation.json')),reconFile=readJson(path.join(dir,'reconciliation.json')),fk=readJson(path.join(dir,'fk_dependency_report.json')),recon=reconFile?.[profile];
const errors=[];if(summary.mode!=='dry-run'||summary.status!=='completed'||status.status!=='completed')errors.push('not-completed-dry-run');if(!sameSet(summary.selectedProfiles,[profile]))errors.push('profile-selection-mismatch');if(!recon)errors.push('reconciliation-missing');if(Number(summary.validationErrors||0)!==0)errors.push('validation-errors');if(Number(summary.requiredLookupMisses||0)!==0)errors.push('required-lookup-misses');if(Number(summary.criticalLookupMisses||0)!==0)errors.push('critical-lookup-misses');if(Number(summary.rejectedRows||0)!==0)errors.push('rejected-rows');if(Number(summary.fkDependencyFailures||0)!==0)errors.push('fk-failures');if(!dbBacked(validation))errors.push('not-db-backed');if(!Array.isArray(fk)||fk.some(r=>r.ok===false))errors.push('fk-report-failed');if(summary.contractHash!==contract.published_contract_sha256)errors.push('contract-hash-mismatch');if(summary.sourceManifestFileSha256!==manifestSha)errors.push('manifest-hash-mismatch');
if(kind==='profile'){
 if(summary.limit!==null||Number(summary.offset||0)!==0||summary.unlimited!==true)errors.push('not-full-profile');if(recon&&(Number(recon.processedRows||0)!==Number(recon.sourceRows||0)||Number(recon.rejectedRows||0)!==0||Number(recon.rolledBackRows||0)!==0))errors.push('profile-reconciliation-failed');
}else{
 const offset=Number(a.offset),limit=Number(a.limit),sourceRows=Number(a['source-rows']);if(!Number.isInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1||limit>500||!Number.isFinite(sourceRows))errors.push('invalid-range-args');if(Number(summary.offset||0)!==offset||Number(summary.limit||0)!==limit||summary.unlimited!==false)errors.push('chunk-range-mismatch');if(recon&&(Number(recon.sourceRows||0)!==sourceRows||Number(recon.processedRows||0)!==limit||Number(recon.rejectedRows||0)!==0||Number(recon.rolledBackRows||0)!==0))errors.push('chunk-reconciliation-failed');
}
if(errors.length){const e=new Error(`${kind} checkpoint failed: ${errors.join(', ')}`);e.code='PHASE7_CHECKPOINT_INVALID';throw e;}
process.stdout.write(`${JSON.stringify({ok:true,kind,profile,dir,summarySha256:sha256File(path.join(dir,'summary.json')),manifestSha256:manifestSha},null,2)}\n`);
