'use strict';
const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
function args(argv){const o={};for(const a of argv){if(!a.startsWith('--'))continue;const [k,...r]=a.slice(2).split('=');o[k]=r.length?r.join('='):true;}return o;}
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'));} function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');}
function sameSet(a,b){const x=[...new Set((a||[]).map(String))].sort(),y=[...new Set((b||[]).map(String))].sort();return x.length===y.length&&x.every((v,i)=>v===y[i]);}
const o=args(process.argv.slice(2)); const mode=String(o.mode||'profile'); const profile=String(o.profile||''); const dir=path.resolve(String(o.dir||'')); const manifestSha=String(o['manifest-sha256']||'').toLowerCase(); const dry=String(o['dry-run-id']||''); const sourceRows=Number(o['source-rows']); const offset=Number(o.offset||0); const limit=o.limit!==undefined?Number(o.limit):null;
const errors=[]; const req=['summary.json','status.json','validation.json','reconciliation.json','fk_dependency_report.json']; for(const f of req) if(!fs.existsSync(path.join(dir,f)))errors.push(`missing:${f}`);
if(errors.length){console.log(JSON.stringify({ok:false,mode,profile,dir,errors},null,2));process.exit(1);} const summary=read(path.join(dir,'summary.json')); const status=read(path.join(dir,'status.json')); const validation=read(path.join(dir,'validation.json')); const recon=read(path.join(dir,'reconciliation.json'))?.[profile]; const fk=read(path.join(dir,'fk_dependency_report.json'));
if(summary.mode!=='live'||summary.status!=='completed'||status.status!=='completed')errors.push('not-completed-live'); if(!sameSet(summary.selectedProfiles,[profile]))errors.push('profile-mismatch'); if(summary.sourceManifestFileSha256!==manifestSha)errors.push('manifest-hash-mismatch'); if(summary.approvedDryRunId!==dry)errors.push('dry-run-mismatch'); if(Number(summary.validationErrors||0)!==0||Number(summary.requiredLookupMisses||0)!==0||Number(summary.criticalLookupMisses||0)!==0||Number(summary.rejectedRows||0)!==0||Number(summary.fkDependencyFailures||0)!==0)errors.push('blocking-findings'); if(!Array.isArray(validation)||!validation.some(r=>r.scope==='db'&&/Connected to MySQL/i.test(String(r.message||''))))errors.push('not-db-backed'); if(!Array.isArray(fk)||!fk.every(r=>r.ok!==false))errors.push('fk-failure'); if(!recon)errors.push('reconciliation-missing');
if(recon){if(Number(recon.sourceRows||0)!==sourceRows)errors.push('source-row-total-mismatch'); if(Number(recon.rejectedRows||0)!==0||Number(recon.rolledBackRows||0)!==0)errors.push('reconciliation-blocking');}
if(mode==='profile'){
  if(summary.offset!==0||summary.limit!==null||summary.unlimited!==true)errors.push('profile-range-not-unlimited'); if(recon&&Number(recon.processedRows||0)!==sourceRows)errors.push('profile-processed-mismatch');
}else if(mode==='chunk'){
  if(Number(summary.offset||0)!==offset||Number(summary.limit||0)!==limit||summary.unlimited!==false)errors.push('chunk-range-mismatch'); if(recon&&Number(recon.processedRows||0)!==limit)errors.push('chunk-processed-mismatch');
}else errors.push('invalid-mode');
const out={ok:errors.length===0,mode,profile,dir,errors,summarySha256:sha(path.join(dir,'summary.json')),statusSha256:sha(path.join(dir,'status.json')),processedRows:recon?Number(recon.processedRows||0):null}; console.log(JSON.stringify(out,null,2)); if(!out.ok)process.exit(1);
