-- Run once immediately after the first successful import and verification.
-- Creates a verification-only idempotency fingerprint table. It does not alter ERP business rows.
-- This is a strong smoke fingerprint (row count + XOR + SUM of CRC32), not a cryptographic proof.
CREATE TABLE IF NOT EXISTS migration_v3_verification_snapshot (
  snapshot_name VARCHAR(50) NOT NULL,
  table_name VARCHAR(100) NOT NULL,
  row_count BIGINT NOT NULL,
  xor_checksum BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sum_checksum DECIMAL(30,0) NOT NULL DEFAULT 0,
  captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (snapshot_name, table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM migration_v3_verification_snapshot WHERE snapshot_name='after_first_import';

INSERT INTO migration_v3_verification_snapshot(snapshot_name,table_name,row_count,xor_checksum,sum_checksum)
SELECT 'after_first_import','pre_costing_data',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',pre_costing_no,buyer,construction)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',pre_costing_no,buyer,construction)) AS UNSIGNED)),0) FROM pre_costing_data UNION ALL
SELECT 'after_first_import','PO_form_data',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',po_no,pre_costing_no,buyer_name,dispo_number)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',po_no,pre_costing_no,buyer_name,dispo_number)) AS UNSIGNED)),0) FROM PO_form_data UNION ALL
SELECT 'after_first_import','dispo_plan_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_no,po_no,buyer,production_construction)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_no,po_no,buyer,production_construction)) AS UNSIGNED)),0) FROM dispo_plan_form UNION ALL
SELECT 'after_first_import','dispo_form_data',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,po_no,precosting_number,buyer_name,production_construction)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,po_no,precosting_number,buyer_name,production_construction)) AS UNSIGNED)),0) FROM dispo_form_data UNION ALL
SELECT 'after_first_import','warp_yarn_details',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,`count`,warp_ply,cal_count,warp_color_name,dyed_qty_kg,grey_qty_kg)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,`count`,warp_ply,cal_count,warp_color_name,dyed_qty_kg,grey_qty_kg)) AS UNSIGNED)),0) FROM warp_yarn_details UNION ALL
SELECT 'after_first_import','weft_yarn_details',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,`count`,weft_ply,cal_count,weft_color_name,dyed_qty_kg,grey_qty_kg)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,`count`,weft_ply,cal_count,weft_color_name,dyed_qty_kg,grey_qty_kg)) AS UNSIGNED)),0) FROM weft_yarn_details UNION ALL
SELECT 'after_first_import','warp_broken_section',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,lower_beam_total_ends,round_no_of_section,fraction_section,fraction_section_ends,remaining_ends)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,lower_beam_total_ends,round_no_of_section,fraction_section,fraction_section_ends,remaining_ends)) AS UNSIGNED)),0) FROM warp_broken_section UNION ALL
SELECT 'after_first_import','warp_broken_pattern',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,warp_color_name,no_of_cones,round_section_yarn,total_fraction_ends,total_required_ends)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,sl_no,warp_color_name,no_of_cones,round_section_yarn,total_fraction_ends,total_required_ends)) AS UNSIGNED)),0) FROM warp_broken_pattern UNION ALL
SELECT 'after_first_import','yarn_receive_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',yarn_count,yarn_brand,yarn_lot,received_start_date,received_against_dispo_nos,challan_no,receipt_qty_kgs)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',yarn_count,yarn_brand,yarn_lot,received_start_date,received_against_dispo_nos,challan_no,receipt_qty_kgs)) AS UNSIGNED)),0) FROM yarn_receive_form UNION ALL
SELECT 'after_first_import','yarn_received_details',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',yarn_receive_form_id,dispo_number,received_date,quantity_kgs)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',yarn_receive_form_id,dispo_number,received_date,quantity_kgs)) AS UNSIGNED)),0) FROM yarn_received_details UNION ALL
SELECT 'after_first_import','yarn_issue_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',yarn_count,yarn_lot,issue_date,received_against_dispo_nos,issue_challan_no,total_received_kg,total_issued_kg,remaining_stock_kg)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',yarn_count,yarn_lot,issue_date,received_against_dispo_nos,issue_challan_no,total_received_kg,total_issued_kg,remaining_stock_kg)) AS UNSIGNED)),0) FROM yarn_issue_form UNION ALL
SELECT 'after_first_import','yarn_issue_details',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',yarn_issue_form_id,dispo_number,issue_date,issued_quantity)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',yarn_issue_form_id,dispo_number,issue_date,issued_quantity)) AS UNSIGNED)),0) FROM yarn_issue_details UNION ALL
SELECT 'after_first_import','warping_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,warping_program_no,warping_date,actual_warp_length_mtr,warping_set,total_no_of_beam)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,warping_program_no,warping_date,actual_warp_length_mtr,warping_set,total_no_of_beam)) AS UNSIGNED)),0) FROM warping_form UNION ALL
SELECT 'after_first_import','warping_breakdown',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',warping_form_id,dispo_number,warping_date,warping_program_no,warping_set,total_beam_no,warping_length_mtr)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',warping_form_id,dispo_number,warping_date,warping_program_no,warping_set,total_beam_no,warping_length_mtr)) AS UNSIGNED)),0) FROM warping_breakdown UNION ALL
SELECT 'after_first_import','sizing_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,warping_program_no,sizing_date,actual_warp_length_mtr,warping_date,warping_set_no,total_warp_beam,actual_sizing_length_mtr)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,warping_program_no,sizing_date,actual_warp_length_mtr,warping_date,warping_set_no,total_warp_beam,actual_sizing_length_mtr)) AS UNSIGNED)),0) FROM sizing_form UNION ALL
SELECT 'after_first_import','sizing_breakdown',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',sizing_form_id,dispo_number,sizing_date,sizing_qty_mtr,total_weavers_beam)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',sizing_form_id,dispo_number,sizing_date,sizing_qty_mtr,total_weavers_beam)) AS UNSIGNED)),0) FROM sizing_breakdown UNION ALL
SELECT 'after_first_import','loom_production_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,weaving_date,in_house_production_day,outside_production_day)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,weaving_date,in_house_production_day,outside_production_day)) AS UNSIGNED)),0) FROM loom_production_form UNION ALL
SELECT 'after_first_import','loom_production_breakdown',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',loom_production_id,dispo_number,loom_production_date,run_loom,loom_production_quantity_yds)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',loom_production_id,dispo_number,loom_production_date,run_loom,loom_production_quantity_yds)) AS UNSIGNED)),0) FROM loom_production_breakdown UNION ALL
SELECT 'after_first_import','folding_production_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,folding_production_date,a_grade_mtr,b_grade_mtr,c_grade_mtr,reject_c_grade_mtr)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,folding_production_date,a_grade_mtr,b_grade_mtr,c_grade_mtr,reject_c_grade_mtr)) AS UNSIGNED)),0) FROM folding_production_form UNION ALL
SELECT 'after_first_import','folding_production_breakdown',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',folding_production_id,dispo_number,loom_production_date,loom_production_qty_yds,folding_production_date,folding_production_qty_yds,folding_balance)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',folding_production_id,dispo_number,loom_production_date,loom_production_qty_yds,folding_production_date,folding_production_qty_yds,folding_balance)) AS UNSIGNED)),0) FROM folding_production_breakdown UNION ALL
SELECT 'after_first_import','greige_delivery_form',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',dispo_number,delivery_date,challan_no,delivery_quantity_a_grade,delivery_quantity_b_grade,delivery_quantity_c_grade,delivery_quantity_reject)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',dispo_number,delivery_date,challan_no,delivery_quantity_a_grade,delivery_quantity_b_grade,delivery_quantity_c_grade,delivery_quantity_reject)) AS UNSIGNED)),0) FROM greige_delivery_form UNION ALL
SELECT 'after_first_import','greige_delivery_breakdown',COUNT(*),COALESCE(BIT_XOR(CAST(CRC32(CONCAT_WS('|',greige_delivery_id,dispo_number,greige_folding_date,greige_folding_qty_yds,greige_delivery_date,greige_delivery_qty_yds,delivery_balance)) AS UNSIGNED)),0),COALESCE(SUM(CAST(CRC32(CONCAT_WS('|',greige_delivery_id,dispo_number,greige_folding_date,greige_folding_qty_yds,greige_delivery_date,greige_delivery_qty_yds,delivery_balance)) AS UNSIGNED)),0) FROM greige_delivery_breakdown;

SELECT * FROM migration_v3_verification_snapshot WHERE snapshot_name='after_first_import' ORDER BY table_name;
