const $=s=>document.querySelector(s);let latest={};
async function jfetch(url,opts={}){const r=await fetch(url,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function loadConfig(){const c=await jfetch('/api/google-config');const tb=$('#sheetTable tbody');tb.innerHTML='';for(const p of c.profiles||[]){const tr=document.createElement('tr');tr.dataset.id=p.id;tr.innerHTML=`<td><strong>${esc(p.label)}</strong><div class="muted">${esc(p.sourceFile)}</div></td><td><input class="sid" value="${esc(p.spreadsheetId)}"></td><td><input class="tab" value="${esc(p.sheetName)}"></td><td><input class="hdr" type="number" min="1" value="${Number(p.headerRow||2)}"></td>`;tb.appendChild(tr);}}
$('#saveSheets').onclick=async()=>{try{const current=await jfetch('/api/google-config');const profiles=[...$('#sheetTable tbody').rows].map(tr=>({id:tr.dataset.id,spreadsheetId:tr.querySelector('.sid').value.trim(),sheetName:tr.querySelector('.tab').value.trim(),headerRow:Number(tr.querySelector('.hdr').value||2)}));await jfetch('/api/google-config',{method:'POST',body:JSON.stringify({profiles})});alert('Saved.');}catch(e){alert(e.message)}};
function render(s){latest=s;$('#dbName').textContent=s.database||'—';$('#sheetCount').textContent=`${s.googleConfigSummary?.configured||0} / ${s.googleConfigSummary?.total||9}`;$('#saStatus').textContent=s.serviceAccountPresent?'Ready':'Missing';$('#currentAction').textContent=s.active?s.active.name:'Idle';$('#overallStatus').textContent=s.active?`Running: ${s.active.name}`:(s.status?.status||'Idle');
 const st=s.status||{};$('#runId').textContent=st.runId||s.state?.activeMigrationRunId||s.state?.latestLiveRunId||s.state?.latestDryRunId||'No run';$('#profile').textContent=st.importer||'—';$('#sourceRow').textContent=st.sourceRowNumber??'—';$('#inserted').textContent=Number(st.inserted||0).toLocaleString();$('#updated').textContent=Number(st.updated||0).toLocaleString();$('#rejected').textContent=Number(st.rejected||0).toLocaleString();$('#rolledBack').textContent=Number(st.rolledBack||0).toLocaleString();const p=Number(st.processed||0),t=Number(st.total||0);$('#rowCounter').textContent=`${p.toLocaleString()} / ${t?t.toLocaleString():'?'}`;$('#progressBar').style.width=t?`${Math.min(100,p/t*100)}%`:'0%';
 const ev=$('#rowEvents');ev.innerHTML=(s.progress||[]).slice().reverse().map(x=>`<div class="row-event"><span>${esc(x.importer)}</span><span>#${esc(x.profileRowNumber)}</span><span class="${['committed','previewed'].includes(x.outcome)?'ok':'bad'}">${esc(x.outcome)}</span><span>${esc(Object.values(x.sourceKeys||{}).slice(0,3).join(' | '))}</span></div>`).join('')||'<div class="muted">No row events yet.</div>';
 $('#consoleLog').textContent=(s.logs||[]).map(x=>x.line).join('\n')||'Waiting for an action…';$('#consoleLog').scrollTop=$('#consoleLog').scrollHeight;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=!!s.active);
}
async function confirmToken(title,text,token){const d=$('#confirmDialog');$('#dialogTitle').textContent=title;$('#dialogText').textContent=`${text} Type ${token} to continue.`;$('#confirmInput').value='';d.showModal();const result=await new Promise(resolve=>{d.addEventListener('close',()=>resolve(d.returnValue),{once:true})});if(result!=='ok')return null;return $('#confirmInput').value.trim();}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=async()=>{const a=b.dataset.action;try{let body={};if(a==='live'){const t=await confirmToken('Start local LIVE migration','This writes 2024–2026 rows into the isolated XAMPP database.','LOCAL-LIVE-MIGRATION');if(!t)return;body.confirm=t;}if(a==='import-db'){const t=await confirmToken('Import local SQL dump','This restores the SQL dump into a new isolated local database. An existing database will not be replaced.','IMPORT-LOCAL-SQL');if(!t)return;body.confirm=t;}await jfetch(`/api/action/${a}`,{method:'POST',body:JSON.stringify(body)});}catch(e){alert(e.message)}};
(async()=>{await loadConfig();render(await jfetch('/api/state'));const es=new EventSource('/events');es.onmessage=e=>{try{render(JSON.parse(e.data));}catch(_){}};es.onerror=()=>{$('#overallStatus').textContent='Dashboard disconnected';};})();
