'use strict';
const assert=require('assert');const {SyncExclusions}=require('../lib/sync_exclusions');
const identity=lot=>({version:1,lot});
const record=(uid,dispo,lot,group=uid)=>({uid,dispo,digest:uid,group,yarnIdentity:identity(lot)});
const a=record('a','nhtml/26/1','lot'),b=record('b','ytml/26/1','other');
const entries=[{profile:'yarn-issue',sourceUid:'a',digest:'a',dispo:a.dispo,lot:'lot'}];
const conflict={profile:'yarn-issue',sourceUid:'a',group:'a',reason:'yarn_identity_backfill_required'};
const initial={ok:false,operations:{'yarn-issue':[{...a,action:'update'},{...b,action:'update'}]},conflicts:[conflict]};
const scope=new SyncExclusions(entries,'skip-dispos');
scope.inspect('yarn-issue',{records:[a,b]},{records:[a,b]},initial);
scope.seal();const result=scope.filter(structuredClone(initial));
assert(result.ok);assert.equal(result.updated,1);assert.equal(result.operations['yarn-issue'][0].dispo,b.dispo,'Different prefix is not the same Dispo');
assert.equal(scope.filter(result).exclusions.skippedOperations['yarn-issue'],1,'A second filtering pass preserves exclusion audit counts');
const {SheetsSyncRuntime}=require('../lib/sheets_sync_runtime');
result.operations['yarn-issue'][0].rowNumber=3;
const runtime=new SheetsSyncRuntime(result,{},'fixture');
assert(!runtime.has('yarn-issue',2),'Excluded source rows are not selected for business or ledger writes');
assert(runtime.has('yarn-issue',3),'Unrelated source rows remain selected');
const dependent=record('c','swml/26/2','lot');
const closure=new SyncExclusions(entries,'skip-dispos');closure.inspect('yarn-issue',{records:[a,b,dependent]},{records:[a,b,dependent]},initial);closure.seal();
assert(closure.dispos.has(dependent.dispo),'Shared yarn-lot dependent Dispo is held');assert(!closure.dispos.has(b.dispo));
assert.throws(()=>new SyncExclusions([{...entries[0],digest:'stale'}]).inspect('yarn-issue',{records:[a]},{records:[a]},initial),/preimage/);
const schema=new SyncExclusions([],'skip-dispos');const hard={ok:false,operations:{},conflicts:[{profile:'po',reason:'schema_changed'}]};schema.seal();assert(!schema.filter(hard).ok);
const removed=new SyncExclusions(entries,'skip-dispos');const added=record('new','scml/26/3','third');
const removedPlan={ok:false,operations:{'yarn-issue':[{...added,action:'insert'}]},conflicts:[conflict]};
removed.inspect('yarn-issue',{records:[a]},{records:[added]},removedPlan);removed.seal();assert(removed.filter(removedPlan).ok);assert.equal(removedPlan.added,0,'Unknown replacement cannot become a duplicate insertion');
const blank=new SyncExclusions([],'skip-dispos');const noDispo={...a,dispo:''};const unbounded={ok:false,operations:{'yarn-issue':[]},conflicts:[conflict]};blank.inspect('yarn-issue',{records:[noDispo]},{records:[]},unbounded);blank.seal();assert(!blank.filter(unbounded).ok);
const defaultScope=new SyncExclusions();defaultScope.inspect('yarn-issue',{records:[a]},{records:[a]},initial);defaultScope.seal();assert(!defaultScope.filter(structuredClone(initial)).ok,'Default still blocks');
assert.equal(a.digest,'a','Original ledger evidence is not changed');
console.log('Sync exclusion tests passed: exact preimages, full prefixes, dependency closure, unknown replacements, schema guards and default blocking.');
